OPENAI_API_KEY = "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"

STRIPE_SECRET_KEY = "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"